### ISSUE TITLE
Cargo clippy error caused by a third-party crate `thiserror-1.0.51`

### ISSUE THREAD

**Issue by Leedehai** [typst/typst#3030]
### Description

`cargo clippy --workspace --all-targets --all-features` is from https://github.com/typst/typst/blob/b1256283da047fd4e2c0ba24d981759c745661bb/.github/workflows/ci.yml#L26

```
$ cargo clippy --workspace --all-targets --all-features
    Checking thiserror v1.0.51
    Checking core_maths v0.1.0
    Checking zerotrie v0.1.2
    Checking approx v0.5.1
    Checking csv-core v0.1.11
    Checking wasmi_arena v0.4.0
    Checking utf8_iter v1.0.4
    Checking icu_segmenter_data v1.4.0
    Checking fast-srgb8 v1.0.0
    Checking icu_properties_data v1.4.0
error[E0554]: `#![feature]` may not be used on the stable release channel
   --> xxx/index.crates.io-6f17d22bba15001f/thiserror-1.0.51/src/lib.rs:238:50
    |
238 | #![cfg_attr(error_generic_member_access, feature(error_generic_member_access))]
    |                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `thiserror` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
```

```
$ git log --format=oneline -n 1 | cat
b1256283da047fd4e2c0ba24d981759c745661bb Added Serbian translation for LocalName (#3023)
```
```
$ cargo version
cargo 1.74.0 (ecb9851af 2023-10-18)
```
```
$ cargo clippy --version
clippy 0.1.74 (79e9716c 2023-11-13)
```

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by Leedehai** [comment]
Fixed after updating from 1.74.0 to 1.74.1
```
$ cargo version
cargo 1.74.1 (ecb9851af 2023-10-18)
```
```
$ cargo clippy --version
clippy 0.1.74 (a28077b2 2023-12-04)
```
